### PR TITLE
Dependencies for the examples

### PR DESCRIPTION
**Pull request by anderslindho**
I noticed that `numpy` was a requirement to use this library.

I suppose that `pyglet` also could be added to this list, but since it technically only is used for the examples that part was less clear to me. I could add it to this MR as an optional feature if you'd like (through use of `extras_requires`).

### CODE REVIEW

**Comment by szabolcsdombi** [comment]
We use `numpy` in a lot of examples, but zengl itself does not depend on `numpy`. There are other libraries that can generate buffer data or simple file content is also sufficient. I really like using `numpy` and it is really well known.

The only dependency at the moment is [`glcontext`](https://github.com/moderngl/glcontext) which has no other open-source alternative yet.
ZenGL itself has 0 dependencies and it has a really small package size as well.
(this is important for the headless mode in a custom environment. also good for my upcoming raspberry pi test)

I like the idea of having `extras_requires` with glcontext and numpy at least, but it would be great to have all the dependencies of the examples.

A MR would be welcome for the `extras_requires`.
Thank you.

**Comment by szabolcsdombi** [comment]
Also [`pyglet`](http://pyglet.org/) is a dependency for most of the examples.

**Comment by anderslindho** [comment]
Like this or do you want `glcontext` as an `install_requires`?

Also, should I close this MR and add one with updated title+description or is this fine?

**Comment by szabolcsdombi** [comment]
This is fine, I update the readme soon to have this pip install offered too.

Is it `pip install zengl[examples]`?

**Comment by anderslindho** [comment]
Correct

**Comment by szabolcsdombi** [comment]
Thank you for your contribution

**Pull request merged**
